[theme]

# Primary accent for interactive elements
primaryColor = '#95E1D3'

# Background color for the main content area
backgroundColor = '#EEEEEE'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#00ADB5'

# Color used for almost all text
textColor = '#222831'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "consolas"
